[package]
name = "gugugaga"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
tokio = { version = "1.53.2", features = ["full"] }
tokio-util = { version = "0.7.19", features = ["codec"] }
futures-util = { version = "0.3.34", default-features = false, features = [
    "sink",
    "std",
] }
hyper = { version = "1.11.1", features = ["http1", "server", "client"] }
simdutf8 = { version = "0.1.5" }
hyper-util = { version = "0.1.21", features = ["tokio"] }
http-body-util = { version = "0.1.5" }
pin-project = { version = "1" }
base64 = { version = "0.22" }
sha1 = { version = "0.10" }
utf-8 = "0.7"
rand = { version = "0.9.5", features = ["small_rng"] }
thiserror = "1"
bytes = "1.12.1"
tokio-rustls = { version = "0.26.6", default-features = false }
rustls = { version = "0.23.45", features = ["std"] }
webpki-roots = "1.0.9"
rustls-pki-types = "1.15.1"
url = "2.5"

[[example]]
name = "client"
path = "examples/client.rs"

[[example]]
name = "client_with_proxy"
path = "examples/client_with_proxy.rs"
